#---- /report ----#

reportMessage: '&6&lReport System &8>>> &7(@reportid) Player &6@player &7reported player &6@reportedplayer&7 with reason:&6 @reason'
reportSent: '&6&lReport System &8>>> &7Report was sent with ID &6%reportId%&7. Reported player: &6%reportedPlayer%&7, reason: &6%reason%'
fewArguments: '&6&lServer &8>>> &7Few arguments! [/report <player> <reason>]'

#---- /report-find ----#

findResult: "&6&lReport System &8>>> &7Informations about report \n&7 Report sender: &6%reporter%\n &7Reported player: &6%reportedPlayer%\n &7Reason: &6%reason%\n &7Timestamp: &6%timestamp%"
findReportUsage: '&6&lServer &8>>> &7Few arguments! [/report-find <id>]'
findResultNotFound: "&6&lReport System &8>>> &7Report with ID &6%reportId%&7 was not found."

#---- /report-done ----#

reportDoneMessage: '&6&lReport System &8>>> &7Report &6%reportId%&7 was marked as solved and was deleted'
reportDoneUsage: '&6&lReport System &8>>> &7Few arguments! [/report-done <id>]'

#---- /report-help ----#

adminHelpCommand: '&6&lReport System &8>>> &7Commands:\n &6/report &7- Command to report a player \n&6 /report-find <ID> &7- command to find report by ID\n &6/report-done <ID> &7- Command to mark the report as solved.'
playerHelpCommand: '&6&lReport System &8>>> &7Use &6/report <player> <reason> &7to report player!'

#---- /report-gui ----# zatím nefunkční

reportGuiLore:
  - "&7Report ID: &e@reportid"
  - "&7Report sender: &e@reporter"
  - "&7Reported player: &e@reportedPlayer"
  - "&7Reason: &e@reason"

#---- /report-list ----#

listPlayersMessage: '&6&lReport System &8>>> &7List of helpers: &6@players'

#---- /report-resethelperlist ----#

resetHelpersMessage: '&6&lReport System &8>>> &7The helper list has been reset.'

#---- REPORTY ----#
reports:
